import type { Product } from "~/lib/domain/entities/product";
import type { ProductRepository } from "~/lib/domain/repositories/product-repository";
import { createProductCode } from "~/lib/domain/value-objects/product-code";

type StaticProduct = Omit<Product, "code" | "updatedAt"> & {
  code: string;
  updatedAt: string;
};

const products: StaticProduct[] = [
  {
    id: "prd-0001",
    code: "FD-DRK-001",
    name: "有機トマトジュース",
    kana: "ユウキトマトジュース",
    brand: "Green Farm",
    category: "飲料",
    tags: ["野菜", "有機", "無塩"],
    allergens: [],
    price: 298,
    packageSize: "720ml",
    description: "完熟有機トマトだけを使った、食塩不使用の濃厚ジュース。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0002",
    code: "FD-DRK-002",
    name: "国産りんごストレートジュース",
    kana: "コクサンリンゴストレートジュース",
    brand: "Aomori Select",
    category: "飲料",
    tags: ["果汁100%", "国産", "子ども向け"],
    allergens: ["りんご"],
    price: 348,
    packageSize: "1L",
    description: "青森県産りんごを搾った香りの良いストレート果汁。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0003",
    code: "FD-RCE-001",
    name: "北海道ゆめぴりか 無洗米",
    kana: "ホッカイドウユメピリカムセンマイ",
    brand: "北の米蔵",
    category: "米・穀物",
    tags: ["北海道", "無洗米", "主食"],
    allergens: [],
    price: 2480,
    packageSize: "5kg",
    description: "甘みと粘りが強い北海道産ゆめぴりかの無洗米。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0004",
    code: "FD-RCE-002",
    name: "もち麦ミックス",
    kana: "モチムギミックス",
    brand: "Daily Grain",
    category: "米・穀物",
    tags: ["食物繊維", "健康", "雑穀"],
    allergens: [],
    price: 398,
    packageSize: "300g",
    description: "白米に混ぜて炊くだけで食感が楽しい国産もち麦。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0005",
    code: "FD-NDL-001",
    name: "全粒粉スパゲッティ",
    kana: "ゼンリュウフンスパゲッティ",
    brand: "Casa Verde",
    category: "麺類",
    tags: ["パスタ", "全粒粉", "輸入"],
    allergens: ["小麦"],
    price: 238,
    packageSize: "500g",
    description: "小麦の香ばしさを感じるデュラム小麦全粒粉パスタ。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0006",
    code: "FD-NDL-002",
    name: "讃岐うどん 乾麺",
    kana: "サヌキウドンカンメン",
    brand: "瀬戸内製麺",
    category: "麺類",
    tags: ["うどん", "乾麺", "常温"],
    allergens: ["小麦"],
    price: 198,
    packageSize: "400g",
    description: "コシのある食感に仕上げた常温保存の讃岐うどん。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0007",
    code: "FD-CND-001",
    name: "減塩丸大豆しょうゆ",
    kana: "ゲンエンマルダイズショウユ",
    brand: "蔵仕込み",
    category: "調味料",
    tags: ["減塩", "和食", "大豆"],
    allergens: ["小麦", "大豆"],
    price: 328,
    packageSize: "500ml",
    description: "丸大豆の旨みを生かしながら塩分を抑えたしょうゆ。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0008",
    code: "FD-CND-002",
    name: "焙煎ごまドレッシング",
    kana: "バイセンゴマドレッシング",
    brand: "Table Plus",
    category: "調味料",
    tags: ["サラダ", "ごま", "濃厚"],
    allergens: ["卵", "小麦", "大豆", "ごま"],
    price: 278,
    packageSize: "380ml",
    description: "焙煎ごまの香りとコクが野菜に合う定番ドレッシング。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0009",
    code: "FD-FRZ-001",
    name: "冷凍ブロッコリー",
    kana: "レイトウブロッコリー",
    brand: "Quick Veg",
    category: "冷凍食品",
    tags: ["野菜", "冷凍", "時短"],
    allergens: [],
    price: 258,
    packageSize: "300g",
    description: "下ゆで済みで弁当や付け合わせに使いやすい冷凍野菜。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0010",
    code: "FD-FRZ-002",
    name: "北海道コーン",
    kana: "ホッカイドウコーン",
    brand: "Quick Veg",
    category: "冷凍食品",
    tags: ["北海道", "野菜", "冷凍"],
    allergens: [],
    price: 228,
    packageSize: "250g",
    description: "甘みのある北海道産とうもろこしを急速冷凍。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0011",
    code: "FD-DRY-001",
    name: "素焼きアーモンド",
    kana: "スヤキアーモンド",
    brand: "Nutri Snack",
    category: "菓子・ナッツ",
    tags: ["ナッツ", "無塩", "おやつ"],
    allergens: ["アーモンド"],
    price: 498,
    packageSize: "180g",
    description: "油と塩を使わず香ばしくローストしたアーモンド。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0012",
    code: "FD-DRY-002",
    name: "ドライマンゴー",
    kana: "ドライマンゴー",
    brand: "Tropical Days",
    category: "菓子・ナッツ",
    tags: ["果物", "ドライフルーツ", "おやつ"],
    allergens: [],
    price: 398,
    packageSize: "120g",
    description: "マンゴーの甘みを凝縮したしっとり食感のドライフルーツ。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0013",
    code: "FD-CAN-001",
    name: "国産さば水煮缶",
    kana: "コクサンサバミズニカン",
    brand: "Blue Ocean",
    category: "缶詰",
    tags: ["魚", "たんぱく質", "常温"],
    allergens: ["さば"],
    price: 248,
    packageSize: "190g",
    description: "国産さばを塩だけで仕上げた料理にも使いやすい水煮缶。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0014",
    code: "FD-CAN-002",
    name: "ツナフレーク オイル無添加",
    kana: "ツナフレークオイルムテンカ",
    brand: "Blue Ocean",
    category: "缶詰",
    tags: ["まぐろ", "ノンオイル", "サラダ"],
    allergens: [],
    price: 168,
    packageSize: "70g",
    description: "サラダやおにぎりに使いやすい、油を加えないツナフレーク。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0015",
    code: "FD-DAI-001",
    name: "成分無調整牛乳",
    kana: "セイブンムチョウセイギュウニュウ",
    brand: "牧場の朝",
    category: "乳製品",
    tags: ["牛乳", "冷蔵", "朝食"],
    allergens: ["乳"],
    price: 238,
    packageSize: "1L",
    description: "生乳100%のすっきり飲みやすい成分無調整牛乳。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0016",
    code: "FD-DAI-002",
    name: "プレーンヨーグルト",
    kana: "プレーンヨーグルト",
    brand: "牧場の朝",
    category: "乳製品",
    tags: ["ヨーグルト", "無糖", "発酵"],
    allergens: ["乳"],
    price: 198,
    packageSize: "400g",
    description: "料理にも使いやすい砂糖不使用のプレーンヨーグルト。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0017",
    code: "FD-BRD-001",
    name: "米粉ロールパン",
    kana: "コメコロールパン",
    brand: "Bake House",
    category: "パン",
    tags: ["米粉", "朝食", "冷凍可"],
    allergens: ["乳"],
    price: 298,
    packageSize: "6個",
    description: "もっちり食感の米粉入りロールパン。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0018",
    code: "FD-BRD-002",
    name: "ライ麦ブレッド",
    kana: "ライムギブレッド",
    brand: "Bake House",
    category: "パン",
    tags: ["ライ麦", "食物繊維", "サンドイッチ"],
    allergens: ["小麦", "乳"],
    price: 328,
    packageSize: "1本",
    description: "ライ麦の酸味と香りを楽しめる食事パン。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0019",
    code: "FD-RTD-001",
    name: "バターチキンカレー",
    kana: "バターチキンカレー",
    brand: "Deli Kitchen",
    category: "レトルト",
    tags: ["カレー", "レトルト", "電子レンジ"],
    allergens: ["乳", "小麦", "鶏肉"],
    price: 298,
    packageSize: "180g",
    description: "トマトとバターのコクを生かしたまろやかなレトルトカレー。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "prd-0020",
    code: "FD-RTD-002",
    name: "野菜たっぷりミネストローネ",
    kana: "ヤサイタップリミネストローネ",
    brand: "Deli Kitchen",
    category: "レトルト",
    tags: ["スープ", "野菜", "温めるだけ"],
    allergens: ["大豆"],
    price: 268,
    packageSize: "200g",
    description: "豆と野菜を煮込んだ具だくさんの常温スープ。",
    updatedAt: "2026-04-30T00:00:00.000Z",
  },
];

export class StaticProductRepository implements ProductRepository {
  async listProducts(): Promise<Product[]> {
    return products
      .map((product) => ({
        ...product,
        code: createProductCode(product.code),
        tags: [...product.tags],
        allergens: [...product.allergens],
        updatedAt: new Date(product.updatedAt),
      }))
      .sort((left, right) =>
        left.category.localeCompare(right.category, "ja") ||
        left.name.localeCompare(right.name, "ja"),
      );
  }
}
